language: java
jdk:
  - oraclejdk8

script: 
  - ant init_all
  - ant compile
  - ant init_tests
  - ant compile_tests
  - ant compile_tests_internal
  - ant compile_tests_external
  - ant make_internal
  - ant make_external
  - ant run_tests_all